server.port=8080
spring.application.name=Lesson_45
spring.datasource.url=jdbc:postgresql://localhost:5433/lesson45_db
spring.datasource.username=postgres
spring.datasource.password=qwerty007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
